In [165]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [177]:
red = pd.read_csv("winequality-red.csv")
white = pd.read_csv("winequality-white.csv")

def define_quality_labels(v):
  if v <= 5:
    return 'low'
  if v <= 7:
    return 'medium'
  return 'high'

red.columns = red.columns.str.replace(" ", "_")
white.columns = white.columns.str.replace(" ", "_")

# red['type'] = 0
# white['type'] = 1

# red['quality_label'] = red['quality'].apply(define_quality_labels)
# white['quality_label'] = white['quality'].apply(define_quality_labels)

# white['bound_sulfur_dioxide'] = white['total_sulfur_dioxide'] - white['free_sulfur_dioxide']
# red['bound_sulfur_dioxide'] = red['total_sulfur_dioxide'] - red['free_sulfur_dioxide']

# combined = pd.concat([red, white], ignore_index=True)
# combined['quality_label'] = pd.Categorical(combined['quality_label'], categories=['low', 'medium', 'high'])
# white['quality_label'] = pd.Categorical(white['quality_label'], categories=['low', 'medium', 'high'])


dfml_red = red.copy()
dfml_white = white.copy()

# dfml_white.drop(['total_sulfur_dioxide'], axis=1, inplace=True)

dfml_white.head()

fixed_acidity  volatile_acidity  citric_acid  residual_sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free_sulfur_dioxide  total_sulfur_dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [ ]:
# encoding
# cat_col_encode = pd.get_dummies(dfml_white['quality_label'])
# dfml_white = pd.concat([dfml_white, cat_col_encode], axis=1)
# dfml_white.drop(columns=['free_sulfur_dioxide', 'quality_label', 'quality'], axis=1, inplace=True)
# dfml_white.head()

In [178]:
y = dfml_white['quality']
X = dfml_white.drop(['quality'], axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [179]:
standard_scaler = StandardScaler()
X_train_standard = standard_scaler.fit_transform(X_train)
X_test_standard = standard_scaler.transform(X_test)

In [182]:
# LogisticRegression model
# LR_model = LogisticRegression(solver='liblinear', random_state=42)
LR_model = LogisticRegression(random_state=42, max_iter=10000)

# fit model
LR_model.fit(X_train_standard, y_train)

LogisticRegression(max_iter=10000, random_state=42)

In [183]:
preds = LR_model.predict(X_test_standard)

acc = accuracy_score(y_test, preds)
cm = confusion_matrix(y_test, preds)
print("accuracy: ", acc)
print("confusion_matrix: \n", cm)

#  0.5316326530612245 - scaling
#  0.513265306122449 - nothing

accuracy:  0.5316326530612245
confusion_matrix: 
 [[  0   0   2   2   0   1   0]
 [  0   1  12  12   0   0   0]
 [  0   1 151 137   1   1   0]
 [  0   0  80 323  28   0   1]
 [  0   0  13 133  46   0   0]
 [  0   0   2  25   8   0   0]
 [  0   0   0   0   0   0   0]]


In [161]:
# Random Forest Classifier model
RF_clf = RandomForestClassifier(n_estimators=100, random_state=42)

# fit model
RF_clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [162]:
# predictions
preds = RF_clf.predict(X_test)

# accuracy
acc = accuracy_score(y_test, preds)
cm = confusion_matrix(y_test, preds)

print(acc)
print("confusion_matrix: \n", cm)

# gini, not standarized

0.7051020408163265
confusion_matrix: 
 [[  0   0   1   4   0   0]
 [  0   6  10   9   0   0]
 [  0   3 205  80   3   0]
 [  0   0  63 345  24   0]
 [  0   0   4  68 120   0]
 [  0   0   1   9  10  15]]
